/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestRouter } from "./TestRouter";

export { TestRouter__factory } from "./factories/TestRouter__factory";
